ARCH="arm64"
DESKTOP="lxde"
DISK_SIZE="131072"
DISTRIB="debian"
DNS=""
FS_TYPE="ext4"
GRAPHICS="vnc"
INCLUDE="bootstrap desktop graphics init extra/ssh extra/pulse graphics/vnc"
INIT="run-parts"
INIT_ASYNC="true"
INIT_LEVEL="3"
INIT_PATH="/etc/rc.local"
INIT_USER="root"
LOCALE="en_US.UTF-8"
MOUNTS="/:/mnt/android"
NET_TRIGGER=""
POWER_TRIGGER=""
PULSE_HOST="127.0.0.1"
PULSE_PORT="4712"
SOURCE_PATH="http://ports.ubuntu.com/"
SSH_ARGS=""
SSH_PORT="22"
SUITE="debian_bookworm"
TARGET_PATH="/sdcard/hello.img"
TARGET_TYPE="file"
USER_NAME="user"
USER_PASSWORD="changeme"
VNC_ARGS=""
VNC_DEPTH="16"
VNC_DISPLAY="0"
VNC_DPI="75"
VNC_HEIGHT="1080"
VNC_WIDTH="1920"