ARCH="arm64"
DESKTOP="lxde"
DISK_SIZE="131072"
DISTRIB="ubuntu"
DNS=""
FB_ARGS="-dpi 100 -sharevts vt0"
FB_DEV="/dev/graphics/fb0"
FB_DISPLAY="0"
FB_FREEZE="none"
FB_INPUT="/dev/input/event0"
FB_REFRESH="true"
FS_TYPE="ext4"
GRAPHICS="vnc"
INCLUDE="bootstrap desktop extra/pulse extra/ssh graphics init"
INIT="run-parts"
INIT_ASYNC="true"
INIT_LEVEL="3"
INIT_PATH="/etc/rc.local"
INIT_USER="root"
LOCALE="en_US.UTF-8"
MOUNTS="/:/mnt/android"
NET_TRIGGER=""
POWER_TRIGGER=""
PRIVILEGED_USERS="n20u:aid_inet n20u:aid_sdcard_rw n20u:aid_graphics"
PULSE_HOST="127.0.0.1"
PULSE_PORT="4712"
SOURCE_PATH="http://ports.ubuntu.com/"
SSH_ARGS=""
SSH_PORT="22"
SUITE="noble"
TARGET_PATH="/sdcard/ubuntu_noble.img"
TARGET_TYPE="file"
USER_NAME="n20u"
USER_PASSWORD="choco2013"
VNC_ARGS=""
VNC_DEPTH="16"
VNC_DISPLAY="0"
VNC_DPI="75"
VNC_HEIGHT="1080"
VNC_WIDTH="1920"
X11_DISPLAY="0"
X11_HOST="127.0.0.1"
X11_SDL="false"
X11_SDL_DELAY="15"