# lib/supervisor.sh - GUEST supervisord framework (systemctl replacement in chroot).
# Distro-agnostic (OSMD). Provides the machinery; the actual per-service programs
# (sshd/cron/desktop/x11vnc commands + env) are generated by init (lib/distro/*),
# because their commands depend on what init installed.
#
# Design (locked decision 4):
#   * supervisord runs as ROOT.
#   * control socket chmod 0700 root:root  -> only root/sudo can `supervisorctl`
#     (a systemctl-like privilege gate).
#   * each program drops privilege via `user=` (desktop/x11vnc -> chroot user;
#     sshd/cron -> root). Programs are INDEPENDENT (desktop != vnc).
#   * idempotent: ensure = start only if not already running.

# Standard in-guest paths (absolute, i.e. inside the chroot).
CHD_SV_DIR="/etc/supervisor"
CHD_SV_MAIN="/etc/supervisor/supervisord.conf"
CHD_SV_CONFD="/etc/supervisor/conf.d"
CHD_SV_SOCK="/run/supervisor.sock"
CHD_SV_PID="/run/supervisord.pid"
CHD_SV_LOGDIR="/var/log/supervisor"

# Is supervisord installed inside the guest rootfs?  <path> = instance dir.
chd_sv_installed() {
    _p="$1"
    [ -x "$_p/usr/bin/supervisord" ] || [ -x "$_p/usr/local/bin/supervisord" ] || [ -x "$_p/bin/supervisord" ]
}

# Resolve the supervisord/supervisorctl binary name available in the guest.
_chd_sv_bin() {
    _p="$1"; _which="$2"   # _which = supervisord | supervisorctl
    for _b in "/usr/bin/$_which" "/usr/local/bin/$_which" "/bin/$_which"; do
        [ -x "$_p$_b" ] && { echo "$_b"; return 0; }
    done
    echo ""; return 1
}

# Write the main supervisord.conf (root, socket 0700). Write-once (unless missing).
# <path> = instance dir.
chd_sv_write_main() {
    _p="$1"
    mkdir -p "$_p$CHD_SV_CONFD" "$_p$CHD_SV_LOGDIR" "$_p/run"
    # Always (re)write: the distro's supervisor package ships its own
    # supervisord.conf, so a skip-if-exists would make ours never take effect.
    cat > "$_p$CHD_SV_MAIN" <<CONF
; chd-generated supervisord config. supervisord runs as root; the control
; socket is 0700 root:root so only root/sudo can drive supervisorctl.
[unix_http_server]
file=$CHD_SV_SOCK
chmod=0700
chown=root:root

[supervisord]
environment=PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
logfile=$CHD_SV_LOGDIR/supervisord.log
pidfile=$CHD_SV_PID
childlogdir=$CHD_SV_LOGDIR
user=root
nodaemon=false

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix://$CHD_SV_SOCK

[include]
files=conf.d/*.conf
CONF
    chmod 644 "$_p$CHD_SV_MAIN"
    return 0
}

# Register (or refresh) a supervised program.
#   chd_sv_add_program <path> <name> <command> [user] [environment] [autorestart]
# <command> is the in-guest command line. [environment] is a supervisor
# environment= value (KEY="v",KEY2="v2") or empty.
chd_sv_add_program() {
    # NOTE: POSIX sh has no local scoping. This function is called in a loop by
    # chd_register_services, so its internals use a private _sv* prefix to avoid
    # clobbering the caller's variables (e.g. the caller's $_user).
    _svp="$1"; _svnm="$2"; _svcmd="$3"; _svuser="${4:-}"; _svenv="${5:-}"; _svar="${6:-unexpected}"
    mkdir -p "$_svp$CHD_SV_CONFD"
    _svf="$_svp$CHD_SV_CONFD/$_svnm.conf"
    {
        echo "[program:$_svnm]"
        echo "command=$_svcmd"
        echo "autostart=true"
        echo "autorestart=$_svar"
        echo "startsecs=2"
        echo "startretries=3"
        echo "stopasgroup=true"
        echo "killasgroup=true"
        [ -n "$_svuser" ] && echo "user=$_svuser"
        [ -n "$_svenv" ]  && echo "environment=$_svenv"
        echo "stdout_logfile=$CHD_SV_LOGDIR/$_svnm.log"
        echo "stderr_logfile=$CHD_SV_LOGDIR/$_svnm.err.log"
        echo "stdout_logfile_maxbytes=1MB"
        echo "stderr_logfile_maxbytes=1MB"
    } > "$_svf"
    chmod 644 "$_svf"
    print_message info "supervisor program registered: $_svnm"
}

# Is supervisord currently running inside the guest?
chd_sv_running() {
    _p="$1"
    # pidfile with a live pid (checked from the host via /proc is unreliable across
    # the chroot boundary; the socket is the authoritative signal).
    [ -S "$_p$CHD_SV_SOCK" ]
}

# Start supervisord if not already running (idempotent). Returns:
#   0 started/already-running, 2 not installed (skip), 1 start failed.
# <path> = instance dir.
chd_sv_ensure() {
    _p="$1"
    if ! chd_sv_installed "$_p"; then
        print_message note "supervisord not installed in guest yet (init sets it up) - skipping service manager."
        return 2
    fi
    chd_sv_write_main "$_p"
    if chd_sv_running "$_p"; then
        # A kill -9 (unmount -f / crash) can leave a stale socket FILE behind while
        # /run's tmpfs survives. Verify the daemon actually answers before trusting it.
        if chd_sv_ctl "$_p" pid >/dev/null 2>&1; then
            print_message info "supervisord already running."
            return 0
        fi
        print_message note "stale supervisor socket detected - cleaning up."
        rm -f "$_p$CHD_SV_SOCK" "$_p$CHD_SV_PID" 2>/dev/null
    fi
    _bin="$(_chd_sv_bin "$_p" supervisord)"
    [ -n "$_bin" ] || { print_message error "supervisord binary vanished."; return 1; }
    print_message info "Starting supervisord (root)..."
    # Launch inside the chroot; supervisord daemonizes (nodaemon=false).
    chroot "$_p" /usr/bin/env -i \
        PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
        TERM="${TERM:-xterm}" HOME=/root \
        "$_bin" -c "$CHD_SV_MAIN" >/dev/null 2>&1 || true
    # Verify the control socket actually appears (honest verification).
    _i=0
    while [ "$_i" -lt 10 ]; do
        chd_sv_running "$_p" && { print_message info "[OK] supervisord up (socket present)."; return 0; }
        sleep 0.3; _i=$((_i+1))
    done
    print_message error "supervisord did not create its socket ($CHD_SV_SOCK). See $CHD_SV_LOGDIR/supervisord.log in the guest."
    return 1
}

# supervisorctl passthrough (root-only by socket perms). <path> <args...>
chd_sv_ctl() {
    _p="$1"; { [ "$#" -gt 0 ] && shift; } || true
    _bin="$(_chd_sv_bin "$_p" supervisorctl)"
    [ -n "$_bin" ] || { print_message error "supervisorctl not found in guest."; return 1; }
    chroot "$_p" "$_bin" -c "$CHD_SV_MAIN" "$@"
}

# Re-read conf.d and apply changes (after init adds/edits programs). <path>
chd_sv_reload() {
    _p="$1"
    chd_sv_running "$_p" || return 0
    chd_sv_ctl "$_p" reread >/dev/null 2>&1 || true
    chd_sv_ctl "$_p" update >/dev/null 2>&1 || true
}
